version: 1.1.{build}
image: Visual Studio 2015
install:
- ps: >-
    $installer = "$PSScriptRoot\setup.exe"

    (New-Object System.Net.WebClient).DownloadFile("https://github.com/turbo/AutoIt-CI/releases/download/1/autoit-v3-setup.exe", $installer)

    Start-Process -FilePath $installer -ArgumentList "/S" -NoNewWindow -Wait

before_build:
- ps: >-
    (gc openEbayItems.au3) -replace 'FileVersion, 1.1.0', "FileVersion, 1.1.$Env:APPVEYOR_BUILD_NUMBER" | Out-File -encoding ASCII openEbayItems.au3

build_script:
- cmd: >-
    "%HOMEDRIVE%\Program Files (x86)\AutoIt3\aut2exe\aut2exe.exe"  /in "%CD%\openEbayItems.au3" /out "%CD%\openEbayItems.exe" /nopack /comp 2 /Console

test: off

artifacts:
- path: openEbayItems.exe
